import type { Candidate } from '../src/types/candidate'

export const mockCandidates: Candidate[] = [
  {
    id: 'ivanov',
    name: 'Иванов Иван Иванович',
    position: 'react-middle',
    pos_label: 'React — ведущий программист',
    file: 'Ivanov.pdf',
    email: 'ivanov@email.com',
    phone: '+7 999 123-45-67',
    city: 'Бишкек',
    tg: '@ivanov_dev',
    exp: [['2022-01 — н.в.', 'TechCorp', 'Frontend Developer', '2 г.']],
    total_exp: '~3.5 г.',
    stack: 'React, TypeScript',
    edu: 'КНУ, Информатика, 2020',
    verdict: 'ЧАСТИЧНО',
    vc: 'verdict-orange',
    criteria: [['ok', 'React — есть'], ['no', 'Next.js — нет']],
    summary: 'Хороший разработчик',
    questions: ['Вопрос 1?'],
    status: 'new',
    createdAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'petrova',
    name: 'Петрова Анна Сергеевна',
    position: 'react-middle',
    pos_label: 'React — ведущий программист',
    file: 'Petrova.pdf',
    email: 'petrova@email.com',
    phone: '+996 555 987-654',
    city: 'Ош',
    tg: '@petrova_fe',
    exp: [['2021-03 — н.в.', 'Digital Agency', 'React Developer', '5 г.']],
    total_exp: '~6.5 г.',
    stack: 'React, TypeScript, Next.js',
    edu: 'ОшГУ, Компьютерная инженерия, 2019',
    verdict: 'ПОДХОДИТ',
    vc: 'verdict-green',
    criteria: [['ok', 'React — отлично']],
    summary: 'Отличный разработчик',
    questions: ['Вопрос 2?'],
    status: 'review',
    createdAt: '2026-04-09T14:30:00Z',
  },
  {
    id: 'sidorov',
    name: 'Сидоров Алексей Петрович',
    position: 'react-middle',
    pos_label: 'React — ведущий программист',
    file: 'Sidorov.pdf',
    email: 'sidorov@email.com',
    phone: null,
    city: 'Джалал-Абад',
    tg: '@sidorov_dev',
    exp: [['2024-06 — н.в.', 'WebStudio', 'Junior Developer', '0.8 г.']],
    total_exp: '~0.8 г.',
    stack: 'React, JavaScript',
    edu: 'Джалал-Абадский университет, Информатика, 2024',
    verdict: 'НЕ СООТВЕТСТВУЕТ',
    vc: 'verdict-red',
    criteria: [['no', 'React — мало опыта']],
    summary: 'Junior разработчик',
    questions: ['Вопрос 3?'],
    status: 'rejected',
    createdAt: '2026-04-08T09:15:00Z',
  },
]
